services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: worksync-sql
    environment:
      SA_PASSWORD: "Password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - worksync-network

  backend:
    build:
      context: ./backend
    container_name: worksync-api
    depends_on:
      - sqlserver
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=WorkSyncDb;User Id=sa;Password=Password123;TrustServerCertificate=True;"
    ports:
      - "5000:8080"
    networks:
      - worksync-network

volumes:
  sql_data:

networks:
  worksync-network:
